version: '3.7'

services:
  db:
    container_name: ql_box_db
    image: mariadb
    restart: always
    ports:
        - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
    volumes:
      - type: bind
        source: ./../db/config.cnf
        target: /etc/mysql/conf.d/config.cnf
      - type: bind
        source: ./../db/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
      - /var/ql-box/data:/var/lib/mysql

  adminer:
    container_name: ql_box_adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
