version: '3.7'

services:
    ql-box:
      container_name: ql_box
    build:
      context: ./../../.
      dockerfile: ./dockerfiles/prod/Dockerfile
    restart: always
    environment:
      DB_HOST: ql_box_db
      DB_USER: "${DB_USER}"
      DB_PWD: "${DB_PASSWORD}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_KEY: "${DB_KEY}"
      USER_KEY: /usr/src/app/.pem/user.pem
      PRIVATE_KEY: /usr/src/app/.pem/private.pem
    ports:
      - 3142:3000
    depends_on:
      - ql-box-db
    volumes:
      - /var/ql-box/.pem:/usr/src/app/.pem
    networks:
      - ql-box-net

  ql-box-db:
    container_name: ql_box_db
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
    volumes:
      - type: bind
        source: ./db/config.cnf
        target: /etc/mysql/conf.d/config.cnf
      - type: bind
        source: ./db/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
      - /var/ql-box/data:/var/lib/mysql
    networks:
      - ql-box-net

networks:
  ql-box-net:
    driver: bridge
